#ifndef _CALC_EVENTS_TABLE_ACTIVATOR_
#error Bad #include "calc_events_table.h"
#endif

#ifndef _CALC_EVENTS_TABLE_GUARDIAN_
#define _CALC_EVENTS_TABLE_GUARDIAN_

#include "state_machine.h"

enum {
	STATE_DIGIT = 1,
	STATE_SEPARATOR = 2,
	STATE_OPERATOR = 3,
	STATE_MINUS = 4,
	STATE_PLUS = 5
};

enum {
	EVENT_DIGIT = 1,
	EVENT_SEPARATOR = 2,
	EVENT_OPERATOR = 3,
	EVENT_MINUS = 4,
	EVENT_PLUS = 5,
	EVENT_INVALID = 6
};

static event_table events[] = {
	{ STATE_DIGIT, EVENT_DIGIT, STATE_DIGIT, &digit },
	{ STATE_DIGIT, EVENT_SEPARATOR, STATE_SEPARATOR, &separator },
	{ STATE_SEPARATOR, EVENT_DIGIT, STATE_DIGIT, &digit },
	{ STATE_SEPARATOR, EVENT_SEPARATOR, STATE_SEPARATOR, &separator },
	{ STATE_SEPARATOR, EVENT_OPERATOR, STATE_OPERATOR, &operator },
	{ STATE_SEPARATOR, EVENT_MINUS, STATE_MINUS, NULL },
	{ STATE_SEPARATOR, EVENT_PLUS, STATE_PLUS, NULL },
	{ STATE_MINUS, EVENT_DIGIT, STATE_DIGIT, &negate },
	{ STATE_MINUS, EVENT_SEPARATOR, STATE_SEPARATOR, &negate },
	{ STATE_PLUS, EVENT_DIGIT, STATE_DIGIT, &plus },
	{ STATE_PLUS, EVENT_SEPARATOR, STATE_SEPARATOR, &plus },
	{ STATE_OPERATOR, EVENT_SEPARATOR, STATE_SEPARATOR, &separator },
	{ EOET, EOET, EOET, NULL }
};

static const int initial_machine_state = STATE_SEPARATOR;

#endif

